### ISSUE TITLE
CLI?

### ISSUE THREAD

**Issue by nickforddev** [featurist/codesandbox-example-links#1]
Neat project, probably should expose a CLI? Similarly to how webpack works, sometimes it's not necessary to create a js file that runs the package, like if you just want to use the default options. 

Usage might look like:

```bash
npx codesandbox-example-links readme.md
```

**Comment by artemave** [comment]
You've just described the already existing CLI :)

**Comment by nickforddev** [comment]
LOL well, then you should implement it again! 😆
